# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Lauren Namer
title: Aspiring Change Leader
email: namerlauren@gmail.com
website: https://l-nam.github.io

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: facespics
github_username:  l-nam
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: lauren-n-38033b249
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
additional_links:
- title: lnam.info
  icon: fas fa-globe
  url: https://l-nam.github.io
- title: calendly
  icon: fa fa-calendar
  url: https://calendly.com/namerlauren/30min

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/lauren_pfp1.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Lauren and I'm an aspiring change leader interested in product management, ui/ux research, and human capital strategy. I believe that <mark>people</mark> are at the center of every decision we make. I love finding ways to bridge the <mark>social sciences</mark> with financial analysis to account for the "people part" of strategy as a core facet in decision-making rather than an afterthought. 

 

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Personal Website
        link: https://github.com/l-nam/
        # link_text: Project Website
        additional_links:
          - title:  l-nam/peronsal website
            icon: fab fa-github
            url: https://github.com/l-nam/l-nam.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          The one and only Lauren Namer personal website.

        description: | # this will include new lines to allow paragraphs
          I started this project to learn <mark>Git</mark> as well as have another way to connect with people! I plan to continue updating this site as a means of testing and tracking my progress self teaching <mark>Git</mark> and as a home for other projects, experiences, and ideas.

      - layout: top-middle
        title: Swét
        #link: https://github.com/l-nam/
        # link_text: Project Website
        additional_links:
          #- title:  l-nam/peronsal website
          #  icon: fab fa-github
           # url: https://github.com/l-nam/l-nam.github.io
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          Fitness For You.

        description: | # this will include new lines to allow paragraphs
          Swét was a personalized fitness app aimed to radically disrupt the personal training industry by providing low-cost training with unmatched customization. Though Swét never made it beyond a business model and mockup, the project provided hands-on experience with <mark>customer segmentation, competitive analysis, user research, and marketing.</mark>

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Guidehouse
        link: guidehouse.com
        # link_text: guidehouse.com
        sub_title: SLG Intern
        caption: June 2022 - August 2022
        quote: >
          Supported a state agency with large scale ERP overhaul and implementation
        description: | # this will include new lines to allow paragraphs
            I supported my team in assisting our client, a large state agency, in the business process optimization needed to support modernization of their ERP system including implementation of a novel system. Utilizing <mark>process mapping</mark> I analyzed over 15 legacy and current state processes to expose areas of incompatibility and improvement before future state implementation. In addition I created a standardized process-step template in <mark>MS Visio</mark> and normalized all additional maps developed by my team before being finalized for the client.

      - layout: left
        title: Goizueta Business and Society Institute
        link: https://goizueta.emory.edu/faculty/business-society
        link_text: goizueta.emory.edu/business-society
        sub_title: Consultant
        caption: August 2021 - December 2021
        quote: >
          Helped create a more equitable, inclusive, and green future through the BCorp movement. 
        description: | # this will include new lines to allow paragraphs
            Working alongside a multidisciplinary team of BBA, JD, MBA, and MDP students I supported our client, an Atlanta based startup, in meeting the <mark>environment, sustainability, and governance</mark> (ESG) requirements to achieve BCorp Certification. Leveraging the unique insights of each team members academic and professional experiences we synthesized and implemented ESG recommendations for our client as well as modifications to their business model.

      - layout: left
        title: Goizueta Business School
        link: https://goizueta.emory.edu/
        link_text: goizueta.emory.edu
        sub_title: Teaching Assistant
        caption: August 2021 - December 2021
        quote: >
          Developed and implemented academic coaching material to increase student success.
        description: | # this will include new lines to allow paragraphs
            I collaborated with a team of four other Teaching Assistants to develop supplemental course content for over 130 MBA and BBA students taking Negotiations at Emory University's Goizueta Business School. Student assignments were evaluated for knowledge gaps and individualized, actionable steps were given as feedback for improved course concept comprehension and retention. In addition I designed and led study/review sessions for all students throughout the semester. 

      - layout: left
        title: Emory University
        link: https://emory.edu/
        link_text: emory.edu
        sub_title: Consultant
        caption: June 2021 - August 2021
        quote: >
          Increased vaccine access through human-centered problem solving.
        description: | # this will include new lines to allow paragraphs
            Myself and a team of BBA and MSBA students analyzed and modeled various social drivers of vaccine hesitency amongst Emory University's employee population. Once key drivers were identified, our analysis was used in conjunction with social science theory to develop a COVID-19 education and vaccination campaign targeting employees of Emory University.

      - layout: left
        title: Hospicall
        #link: https://emory.edu/
        #link_text: emory.edu
        sub_title: Intern
        caption: June 2020 - August 2020
        quote: >
          Improved healthcare outcomes through medical technology.
        description: | # this will include new lines to allow paragraphs
            I supported a med-tech startup focused in reducing nurse response times via our product Hospicall. I developed models to determine the benefits and costs associated with various incorporation methods as well as pitch decks for successful acceptance into Hubspot's ELEVATE growth accelerator. While attending ELEVATE I advanced my understandings of <mark>pitch design, go-to market strategy, and customer acquisition.</mark>





  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Emory University Goizueta Business School
        caption: 2018 - 2023
        sub_title: BBA Organization Management | Sociology
        quote: >
          Emory University is a leading research institution guided by its mission to "create, preserve, teach, and apply knowledge in the service of humanity." Emory graduates creative thinkers, problem solvers, and exceptional leaders who work to address some of the world's most complex issues.
        description: | # this will include new lines to allow paragraphs
          I am currently a 5th year Undergrad pursuing a double major in *Organization Management* and *Sociology.* In addition, I am pursuing a secondary area depth in *Business and Society.*

          Outside of class I dedicate most of my time to *TableTalk Emory* and *WMRE - Emory Radio.* I am proud to have served as a former *Co-President* of *TableTalk Emory* and the current *President* of our student radio station. 

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      When I am not spending time on class or my extracurriculars you can catch me:
      - Cooking
      - DJing
      - Producing Electronic Music
      - Hiking


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
